variable "env" {}
variable "app_name" {}
variable "subnet_id" {}
variable "solution-stack" {}
variable "db_username" {}
variable "db_name" {}
variable "db_password" {}
variable "db_endpoint" {}
variable "domain" {}
variable "key_name" {}
variable "vpc_id" {}
variable "soa_endpoint" {}
variable "image_id" {}
variable "dns_zone" {}
